modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="back_in_classic"
<<<<<<< Updated upstream
version="0.6.0-alpha.1"
=======
version="0.8.0-alpha.2-ex1"
>>>>>>> Stashed changes

displayName="Back In Classic"
credits="https://www.curseforge.com/members/saishogaming/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/back-in-classic \n https://github.com/MantisYT5818/Back-in-Classic"
logoFile="logo.png"
authors="Saisho (MantisYT), Charles445"
description='''
Bringing back Classic Features with new functions!
'''

[[dependencies.back_in_classic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.back_in_classic]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

